#ifndef __SIMPLE_LINEAR_STACK_C_TESTING_DEFINITION_HEADER__
#define __SIMPLE_LINEAR_STACK_C_TESTING_DEFINITION_HEADER__
#include <tree/C/treelib_extern.h>


TREELIB_EXTERNC_DECL_BEGIN

int run_all_stack_tests(void);

TREELIB_EXTERNC_DECL_END


#endif /* __SIMPLE_LINEAR_STACK_C_TESTING_DEFINITION_HEADER__ */
