#ifndef __TREELIB_API_EXTERN_C_DEFINITION_MACRO
#define __TREELIB_API_EXTERN_C_DEFINITION_MACRO
#ifdef __cplusplus
#   define TREELIB_EXTERNC extern "C"
#   define TREELIB_EXTERNC_DECL_BEGIN TREELIB_EXTERNC {
#   define TREELIB_EXTERNC_DECL_END   }
#else
#   define TREELIB_EXTERNC
#   define TREELIB_EXTERNC_DECL_BEGIN
#   define TREELIB_EXTERNC_DECL_END
#endif
#endif