#include "binaryTreePrettyPrint.hpp"
#include <string>
#include <vector>
#include <string>
#include <sstream>




struct cell_display {
    std::string valstr;
    bool        present;
    cell_display() : present(false) {}
    cell_display(std::string valstr) : valstr(valstr), present(true) {}
};


using display_rows = std::vector< std::vector< cell_display > >;


static display_rows get_row_display(binaryTree* root) {
    std::vector<binaryTree*> traversal_stack;
    std::vector< std::vector<binaryTree*> > rows;
    if(!root) return display_rows();

    binaryTree *p = root;
    const int max_depth = root->m_height;
    rows.resize(max_depth);
    int depth = 0;
    for(;;) {
        // Max-depth Nodes are always a leaf or null
        // This special case blocks deeper traversal
        if(depth == max_depth-1) {
            rows[depth].push_back(p);
            if(depth == 0) break;
            --depth;
            continue;
        }

        // First visit to node?  Go to m_left child.
        if(traversal_stack.size() == depth) {
            rows[depth].push_back(p);
            traversal_stack.push_back(p);
            if(p) p = p->m_left;
            ++depth;
            continue;
        }
    
        // Odd child count? Go to m_right child.
        if(rows[depth+1].size() % 2) {
            p = traversal_stack.back();
            if(p) p = p->m_right;
            ++depth;
            continue;
        }

        // Time to leave if we get here

        // Exit loop if this is the root
        if(depth == 0) break;

        traversal_stack.pop_back();
        p = traversal_stack.back();
        --depth;
    }

    // Use rows of Node pointers to populate rows of cell_display structs.
    // All possible slots in the tree get a cell_display struct,
    // so if there is no actual Node at a struct's location,
    // its boolean "present" field is set to false.
    // The struct also contains a string representation of
    // its Node's value, created using a std::stringstream object.
    display_rows rows_disp;
    std::stringstream ss;
    for(const auto& row : rows) {
        rows_disp.emplace_back();
        for(binaryTree* pn : row) {
            if(pn) {
                ss << pn->m_data;
                rows_disp.back().push_back(cell_display(ss.str()));
                ss = std::stringstream();
            } else {
                rows_disp.back().push_back(cell_display());
    }   }   }
    return rows_disp;
}

// row_formatter takes the std::vector of rows of cell_display structs 
// generated by get_row_display and formats it into a test representation
// as a std::vector of strings
static std::vector<std::string> row_formatter(const display_rows& rows_disp) {
    using s_t = std::string::size_type;


    // First find the maximum value string length and put it in cell_width
    s_t cell_width = 0;
    for(const auto& row_disp : rows_disp) {
        for(const auto& cd : row_disp) {
            if(cd.present && cd.valstr.length() > cell_width) {
                cell_width = cd.valstr.length();
    }   }   }

    // make sure the cell_width is an odd number
    if(cell_width % 2 == 0) ++cell_width;

    // allows leaf nodes to be connected when they are
    // all with size of a single character
    if(cell_width < 3) cell_width = 3;


    // formatted_rows will hold the results
    std::vector<std::string> formatted_rows;

    // some of these counting variables are related,
    // so its should be possible to eliminate some of them.
    s_t row_count = rows_disp.size();

    // this row's element count, a power of two
    s_t row_elem_count = 1 << (row_count-1);

    // m_left_pad holds the number of space charactes at the beginning of the bottom row
    s_t m_left_pad = 0;

    // Work from the level of maximum depth, up to the root
    // ("formatted_rows" will need to be reversed when done) 
    for(s_t r=0; r<row_count; ++r) {
        const auto& cd_row = rows_disp[row_count-r-1]; // r reverse-indexes the row
        // "space" will be the number of rows of slashes needed to get
        // from this row to the next.  It is also used to determine other
        // text offsets.
        s_t space = (s_t(1) << r) * (cell_width + 1) / 2 - 1;
        // "row" holds the line of text currently being assembled
        std::string row;
        // iterate over each element in this row
        for(s_t c=0; c<row_elem_count; ++c) {
            // add padding, more when this is not the m_leftmost element
            row += std::string(c ? m_left_pad*2+1 : m_left_pad, ' ');
            if(cd_row[c].present) {
                // This position corresponds to an existing Node
                const std::string& valstr = cd_row[c].valstr;
                // Try to pad the m_left and m_right sides of the value string
                // with the same number of spaces.  If padding requires an
                // odd number of spaces, m_right-sided children get the longer
                // padding on the m_right side, while m_left-sided children
                // get it on the m_left side.
                s_t long_padding = cell_width - valstr.length();
                s_t short_padding = long_padding / 2;
                long_padding -= short_padding;
                row += std::string(c%2 ? short_padding : long_padding, ' ');
                row += valstr;
                row += std::string(c%2 ? long_padding : short_padding, ' ');
            } else {
                // This position is empty, Nodeless...
                row += std::string(cell_width, ' ');
            }
        }
        // A row of spaced-apart value strings is ready, add it to the result std::vector
        formatted_rows.push_back(row);
    
        // The root has been added, so this loop is finsished
        if(row_elem_count == 1) break;

        // Add rows of forward- and back- slash characters, spaced apart
        // to "connect" two rows' Node value strings.
        // The "space" variable counts the number of rows needed here.
        s_t m_left_space  = space + 1;
        s_t m_right_space = space - 1;
        for(s_t sr=0; sr<space; ++sr) {
            std::string row;
            for(s_t c=0; c<row_elem_count; ++c) {
                if(c % 2 == 0) {
                    row += std::string(c ? m_left_space*2 + 1 : m_left_space, ' ');
                    row += cd_row[c].present ? '/' : ' ';
                    row += std::string(m_right_space + 1, ' ');
                } else {
                    row += std::string(m_right_space, ' ');
                    row += cd_row[c].present ? '\\' : ' ';
                }
            }
            formatted_rows.push_back(row);
            ++m_left_space;
            --m_right_space;
        }
        m_left_pad += space + 1;
        row_elem_count /= 2;
    }

    // Reverse the result, placing the root node at the beginning (top)
    std::reverse(formatted_rows.begin(), formatted_rows.end());

    return formatted_rows;
}

// Trims an equal number of space characters from
// the beginning of each string in the std::vector.
// At least one string in the std::vector will end up beginning
// with no space characters.
static void trim_rows_m_left(std::vector<std::string>& rows) {
    if(!rows.size()) return;
    auto min_space = rows.front().length();
    for(const auto& row : rows) {
        auto i = row.find_first_not_of(' ');
        if(i== std::string::npos) i = row.length();
        if(i == 0) return;
        if(i < min_space) min_space = i;
    }
    for(auto& row : rows) {
        row.erase(0, min_space);
    }
    return;
}




class Solution {
private:

    // Recursive function to fill the grid
    static void fill(std::vector<std::vector<std::string>>& res, binaryTree* node, int row, int left, int right) {
        // Essential boundary checks to prevent the "trap" / out-of-bounds access
        if (!node || row >= node->m_height || left > right) {
            return;
        }
        
        // Use the safe midpoint calculation
        int mid = left + (right - left) / 2;
        
        // Double-check bounds for debug builds before assignment
        if (mid >= 0 && mid < static_cast<int>(res[row].size())) {
            res[row][mid] = std::to_string(node->m_data);
        }
        
        // Recurse to children with halved boundaries
        fill(res, node->m_left, row + 1, left, mid - 1);
        fill(res, node->m_right, row + 1, mid + 1, right);
        return;
    }

public:
    static std::vector<std::vector<std::string>> printTree(binaryTree* root) {
        if (!root) return {};

        int width = (1 << root->m_height) - 1; 
        std::vector<std::vector<std::string>> res(root->m_height, std::vector<std::string>(width, ""));
        
        fill(res, root, 0, 0, width - 1);
        
        return res;
    }
};




void DumpBinaryTree(FILE* outputFile, binaryTree* root)  {
    // If this tree is empty, tell someone
    fprintf(outputFile, "Tree @%p\n", root);
    if(binaryTree::isLeaf(root)) {
        fprintf(outputFile, "Single Leaf Of Value %u\n", root->m_data);
        return;
    } else if(binaryTree::singleChildParent(root)) {
        fprintf(outputFile, "    %u\n", root->m_data);
        fprintf(outputFile, "%*u\n", root->m_left ? 0 : 8, root->m_left ? root->m_left->m_data :  root->m_right->m_data);
        return;
    }


    const auto rows_disp = get_row_display(root);
    auto formatted_rows = row_formatter(rows_disp);
    trim_rows_m_left(formatted_rows);
    for(const auto& row : formatted_rows) {
        fprintf(outputFile, " %s\n", row.c_str());
    }
    return;
}


void printBinaryTree(FILE* outputFile, binaryTree* root)
{
    auto treePrettyPrintVector = Solution::printTree(root);
    for(auto& row : treePrettyPrintVector) {
        for(auto& column : row) {
            if(column.size() == 1 && column.c_str()[0] == '\0') {
                fprintf(outputFile, " ");
            } else {
                fprintf(outputFile, "%s\n", column.c_str());
            }
        }
    }
}




